version: '3.9'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - "OLLAMA_HOST=http://ollama:11434"
    depends_on:
      - ollama
volumes:
  ollama:
